Develop
silabs-EricZhao/How-to-optimize-the-current-consumption-of-Long-Preamble-Duty-Cycle-application-on-FG14 pull request #1
Opened 2021-09-22 11:25 UTC by silabs-EricZhao

2021-09-23 02:03 UTC, silabs-JimL reviewed
Just a few minor comments. @silabs-EricZhao

2021-09-23 02:03 UTC, JimTech-IoT commented on README.md
> +But in example project, there still a huge room to improve the power consumption. Here is the test result for **Long Preamble Duty Cycle** example.
1. It's better to use "sample" instead of "example".
2. in "the" sample project.  --- better to add "the" in the sentence.
3. there is

2021-09-23 02:03 UTC, JimTech-IoT commented on README.md
> +11. Finally, type **Ctrl+S** to save the current configuations. the radio generator will automatically generate the relevant codes.
Ctrl+S  --- not displayed as expected

2021-09-23 02:03 UTC, JimTech-IoT commented on README.md
> +- Modify the funcations as following.
1. functions  -- no 'a' after 'c'
2. This line "Modify the funcations as following.  " is not displayed as expected. Better to add a new line before it.

2021-09-23 02:03 UTC, silabs-JimL commented on README.md
> +[KBA: Understanding DSSS Encoding and Decoding on EFR32 Devices](https://community.silabs.com/s/article/understanding-dsss-encoding-and-decoding-on-efr32-devices?language=en_US)
Better to make the references as a list

2021-09-23 02:06 UTC, silabs-JimL commented on README.md
> +Please download the ***rail_config.c*** and ***rail_config.h*** file as the following link, and replace the original file in **Autogen** folder.
Add a reminder here that these two files will be overwritten if the customer changes anything in RadioConfigurator.

2021-09-29 02:10 UTC, silabs-LeiSun requested changes

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +But in the sample project, there is still a huge room to improve the power consumption.
The Flex SDK provides the Long Preamble Duty Cycle example application which is widely used by lots of customers in different industry scenarios like Smart Meter, Smart Medica, etc. In most of the use cases, the product is working in duty cycle mode(more details please refer to this KBA) with DSSS long-range PHY to save power energy and in the meanwhile to reach a long communication distance. As the device is always powered by a battery, we expect to reduce the average power consumption of the device as much as possible.

This article introduces a way to optimize the average power consumption of the Long Preamble Duty Cycle example application with the DSSS long-range PHY and provides a step-by-step guide to verify the solution on the BRD4261A radio board. The test result demonstrates the average power consumption decreases a lot after applying the optimized radio configuration.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +# How to improve the power consumption of LDC on BDR4261A
How to optimize the current consumption of Long Preamble Duty Cycle application on FG14

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +## Preparation
Hardware Required

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +    - BDR4261A (EFR32FG14P233F256GM48)
- One BRD4261A (EFR32FG14P233F256GM48)
    - Signal generator: E4432B
    - Spectrum analyzer: MS2692A 
    - Power analyzer: N6705C

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +- Software
Software Required

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +    - Power analyzer: N6705C
Remove

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +    - Radio configuations: Long Range profile 490M 9.6Kbps
- Radio Configurator: Long Range Profile with 490M 9.6 kbps OQPSK DSSS

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +## How to improve the power consumption
The theoretical analysis of the  power consumption

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +- Reduce the Rx on time
From the above analysis, we probably have two methods to decrease the average power consumption: one is to decrease the sleep current, another is to reduce the Rx on time.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +## Creat a Long preamble duty cycle example project and configure it
How to create the Long Preamble Duty Cycle example application in Simplicity Studio

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +2.  Go to **Project**->**New**->**Silicon Labs Wizard...**
You should click the "Simplicity IDE" perspective first!!!!

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +3.  Choose the board or device, select the SDK version V3.2.1, and then choose the **NEXT**.
3.  Choose the board or device(we choose BRD4261A here), select the SDK version V3.2.1 and IAR or GNU ARM Toolchain, and then click the **NEXT**.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +4.  In the left **Technology type** tab, choose the **propriety**.
In the left **Technology Type** tab, choose the **Propriety**.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +5.  In the right example list, choose **Felx(RAIL)-Long Preamble Duty Cycle** example, and then choose the **NEXT** and click **FINISH**.
In the right example list, choose **Flex(RAIL)-Long Preamble Duty Cycle** example, and then click **NEXT**. You can modify the Project name and then click **FINISH**.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +6.  Find the **.slp** file in project and open it, choose the **CONFIGURATION TOOLS** and select **Radio Configurator**.
Double click the **long_preamble_duty_cycle.slcp** file in the Project Explorer and open it, then click the **CONFIGURATION TOOLS** and click the **open** the Radio Configurator.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +7. In the **General Settings** field, select the radio profile **Long Range Profile**,select the radio PHY **434MHz 9.6Kbps OQPSK DSSS SF8**.
In the **General Settings**, choose the **Long Range Profile** in the Select radio profile area, and choose the **434MHz 9.6 kbps OQPSK DSSS SF8** in the Select radio PHY area.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +8. Enable **Customized**, in the **Operational Frequency** field, fill the **Base Channel Frequency** to **490MHz**.
Enable the **Customized** button, set the **Base Channel Frequency** to **490MHz** in the **Operational Frequency** area.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +9. In the **Other settings** field, make sure the **Long Range Mode** is **LR_9p6k**.
In the **Other settings** area, set the **Long Range Mode** to **LR_9p6k**.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +10. Radio configuations as the following figure.
Below is the detail of the Radio Configuration for your reference.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +11. Finally, type **Ctrl+S** to save the current configuations. the radio generator will automatically generate the relevant codes.
Finally, type **Ctrl+S** to save the radio configurations. The relevant codes will be generated automatically in the project.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +## How to optimize the current in EM2 mode
Remove the unused peripherals to optimize the EM2 current

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +EFR32xG14 sleep current in EM2 mode can be as low as **1.3uA**. Please refer to the datasheet, [ERF32FG14 datasheet](https://www.silabs.com/documents/public/data-sheets/efr32fg14-datasheet.pdf).
Move this sentence to the "Test the sleep current" part.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +    - Find the LED control funtions in *app_init.c* file and *app_process.c* file and then comment it.
Use the sequential numerical order as above:

12. **Uninstall LED driver**  
    - Go to the "long_preamble_duty_cycle.slcp" file, click the **SOFTWARE COMPONENTS**, and search **LED** in software components. You can see the **Simple LED** component under Driver, click the **Uninstall** and delete the led0 and led 1 instance, click **Done**.

Note: if anything needs to be modified in the .c or .h file, you can introduce it later, instead of mix it in the section. In there, we should focus on modifying the software components only.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +    - Find the LED control funtions in *app_init.c* file and *app_process.c* file and then comment it.
For last step, what's the LED control functions in *app_init.c* file and *app_process.c*? Please list the detailed functions here.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +    -  Search **Button**, Uninstall the Button instance.
- Search **Button**, click the **Simple Button** component, and then click **Uninstall**, check the **btn0** and click **Done** in the pop-up dialog.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   -  Search **RAIL Utility**, uninstall the **RAIL Utility, Recommended** component of the PTI.
-  Search **RAIL Utility**, click the  **RAIL Utility, Recommended** component, and then click **Uninstall**, the **RAIL Utility, PTI** component will be uninstalled.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   -  Search the **Graphics**, uninstall the **GLIB Graphics Library** component.
- Search **Graphics**, click the **GLIB Graphics Library** component and then click **Uninstall**.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   -  Find the .pintool file and open it, change the unused GPIO mode to **None** as the fllowing figure.
- Go to the "CONFIGURATION TOOLS" tab and click **open** on the right of the **Pin Tool**, configure the unused GPIO mode to **None**, below is the configuration for your reference:

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +      <img src="images/PIN tool configuration.png" width="50%" height="50%">
How about other Pins??

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +      <img src="images/PIN tool configuration.png" width="50%" height="50%">
The modification in the Pin Tools is in a different area from the Software Component, you should complete the introduction of all the modifications and then introduce the modification for Pin Tools. So the order will be:
1. Modification for Software Component
2. Modification for Pin Tools
3. Modification for .c and .h files

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   -  Search **board control** in software components, and click **configurate**. In the **Genteral** field, disable the **Enable Virtual COM UART** button.
-  Search **Board Control** in software components, and click the **Configure** button. In the **General** area, disable the **Enable Virtual COM UART** button.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   -  Try to modify the ***void sli_power_manager_handle_pre_deepsleep_operations(void)*** and ***void sli_power_manager_restore_high_freq_accuracy_clk(void)***, Simplicity Studio will pops up a warn
- Open the ***sl_power_manager_hal_s0_s1.c*** in the project folder: gecko_sdk_3.2.2->platform->service->power_manager->src.
 - Modify the ***void sli_power_manager_handle_pre_deepsleep_operations(void)*** and ***void sli_power_manager_restore_high_freq_accuracy_clk(void)*** functions as below code snippets. Note: you will see a pop-up warning box when modifying the code, click **Make a Copy** to copy the this file from SDK library to the project workspace.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   - Modify the functions in ***sl_power_manager_hal_s0_s1.c*** file as the follows.
Remove

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   -  Include The TCXO control head file. Add the ***#include "sl_board_control.h"*** to this file.
Remove this line. Provide a code snippet of the include header file instead.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +8. **Calculate the minimum of Rx on time**
**Configure the Duty Cycle**

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +   - Find ***the sl_duty_cycle_config.h*** in **config** catalog, and Modify the macro **DUTY_CYCLE_ON_TIME** to 4167.
- Open the ***sl_duty_cycle_config.h*** in the **config** folder, and modify the macro **DUTY_CYCLE_ON_TIME** to 4167.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +Find the ***the sl_duty_cycle_config.h*** file as above, and enable EM2 mode and disable button as following.
- Open the ***sl_duty_cycle_config.h*** file in the config folder, enable EM2 mode and disable button as following.

2021-09-29 02:10 UTC, silabs-LeiSun commented on README.md
> +10. **Build project and flash to device**
**Build the project and flash the firmware**

2021-09-29 02:30 UTC, silabs-LeiSun requested changes

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +    - After compiling is completed, find the binary file is located in **binaries** catalog, right click->**Flash to device...**->**choose the target device**->**OK**.
- Click the hammer icon to build the project.
    - After compiling is completed, the .s37 binary file is located at **binaries** folder, right-click the .s37 binary and choose **Flash to device...**->**choose the target device**->**OK**.

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +### Test the sleep current
Measure EM2 current consumption

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +-  Build the project and flash the hex file to target board.
Delete

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +-  Use the instrument to test sleep current. The sleep current as the following figure.
- We use the power analyzer N6705C to measure the EM2 current consumption and get the average current consumption is about 1.94uA. For more info about how to measure the sleep current please refer to ANxxxx.

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +The sleep current is **1.94uA** after disable TCXO and unused GPIO. Due to there still some GPIO is working, so the result is in accord with the data from datasheet.
According to the EFR32FG14 datasheet, the above EM2 current consumption is close to the value mentioned in the datasheet. There still several peripherals are in use so the test result is expected.

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +## How to optomize the Rx on time
Apply the optimized Radio Configuration for the DSSS long-range PHY

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +In the sample project, the Rx on time is a fixed time even there is no any carrier in air. An appropriate approach is that radio will fast go to sleep when no any preamble is detected.
Delete.

Silicon Labs has provided an optimized Long Range PHY with 490M 9.6 kbps OQPSK DSSS to reduce the average consumption. Below is the guide to applying it to the project.

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +### Modity the timing of Preamble detection
### Modify the timing of the preamble detection

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +-  Add the macro to ***sl_duty_cycle_config.h*** file as following.
-  Add the below macro to the ***sl_duty_cycle_config.h*** file

2021-09-29 02:30 UTC, silabs-LeiSun commented on README.md
> +-  Add the macro to ***app_init.c*** file as following.
- Add the below macro to the ***app_init.c*** file

2021-09-29 02:42 UTC, silabs-LeiSun requested changes

2021-09-29 02:42 UTC, silabs-LeiSun commented on README.md
> +-  Define the variable in ***app_init.c*** file and configurate the timing of duty cycle as following.
- Add the define of the ***duty_cycle_multi_mode_config*** and configure the ***duty_cycle_config*** in the ***app_init.c*** file as following:

2021-09-29 02:42 UTC, silabs-LeiSun commented on README.md
> +-  Please find the ***sl_duty_utilicy.c*** file in the path ***gecko_sdk_3.2.1/app/flex/component/rail/sl_duty_cycle_core*** and modify the funcation of calculating preamble bit length as following.
-  Open the ***sl_duty_utilicy.c*** file in the folder ***gecko_sdk_3.2.2->app->flex->component->rail->sl_duty_cycle_core*** and modify the ***calculate_preamble_bit_length_from_time*** function as following. Please choose **Make a Copy** when you modify the file.

2021-09-29 02:42 UTC, silabs-LeiSun commented on README.md
> +### Modify the Radio PHY configuations
### Override the Radio Configuration

2021-09-29 02:42 UTC, silabs-LeiSun commented on README.md
> +Please download the ***rail_config.c*** and ***rail_config.h*** file as the following link, and replace the original file is located in **Autogen** folder, rebuild the project and flash to the device
- Please download the ***rail_config.c*** and ***rail_config.h*** file from the below link, and replace the original files located in the **Autogen** folder.

 - Rebuild the project, and flash the firmware to the device.

2021-09-29 02:42 UTC, silabs-LeiSun commented on README.md
> +## Test conclusion
Test Result

2021-09-29 02:56 UTC, silabs-LeiSun requested changes

2021-09-29 02:56 UTC, silabs-LeiSun commented on README.md
> +After optimzing the EM2 current and radio PHY. **Iavg = 19.036 uA**
Delete

2021-09-29 02:56 UTC, silabs-LeiSun commented on README.md
> +**Conclusion:** The power consumption reduce by **53%** to **19.036 uA** after optimizing.
The average current consumption of the sample project with optimized radio configuration is 19.04uA, which is much better than the average current consumption of the original sample project. From the table, the average current consumption reduces 53%, which is a very huge improvement.

2021-09-29 02:56 UTC, silabs-LeiSun commented on README.md
> +Below table is the comparison of power consumption between the sample project and the optimized project.
The below table is the comparison of power consumption between the sample project with and without the optimization.

2021-09-29 02:56 UTC, silabs-LeiSun commented on README.md
> +|**average current**| 40.674 uA| 19.036 uA |
|   Project   |Original Project| Optimized Project| 
|:----:| :-----------:| :----------------:| 
|**Average Current**| 40.674 uA| 19.036 uA |

2021-09-29 03:18 UTC, silabs-LeiSun requested changes

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +-  Sensitivity is **-118.4 dBm** after optimizing. Below table shows the test data.
- We use the [LR_Waveform_Generator](https://github.com/silabs-JimL/LR_WaveFormGenerator) and E4432B signal generator to measure the conducted sensitivity. Below is the test result, we can see the sensitivity of the optimized project is **-118.4 dBm***.

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +    |-118.3 dBm| 1000 | 994 |
|  Output Power    |Tx Packets| Rx Packets| 
    |:----:| :-----------:| :----------------:| 
    |-119.2 dBm| 1000 | 974 |
    |-118.8 dBm| 1000 | 982 |
    |-118.6 dBm| 1000 | 989 |
    |-118.5 dBm| 1000 | 987 | 
    |**-118.4 dBm**| **1000** | **991** |
    |-118.3 dBm| 1000 | 994 |

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +-  The sensitivity of original long preamble duty cycle is **-119.2 dBm**. Below table shows the test data.
-  The sensitivity of the original long preamble duty cycle project is **-119.2 dBm**.

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +    |  output power    |Tx packets| Rx packets|
|  Output Power    |Tx Packets| Rx Packets|

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +
The below table includes the comparison of sensitivity between the sample project and the optimized project.

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +    |   project   |sample peoject| optimized project|
|   Project   |Sample Project| Optimized Project|

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +  **Conclusion:** Compared with original example, there is a **0.8 dBm** loss on sensitivity. But the loss is trivial and the optimization is well worth to do it.
The sensitivity of the sample project with optimized radio configuration reduces about **0.8 dBm**, which is insignificant and can be accepted by customers in order to get better power consumption.

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +So far this tutorial is only for **9.6kbps**. If you want to optimize it for 1.2kbps or 19.2kbps, please contact with the slicion labs FAE.
We only provide the optimized radio configuration for **9.6kbps** on EFR32FG14 in this project, which can be covered for most of the use cases that power consumption is sensitive. Please feel free to contact the Silicon Labs FAE or Sales team if you have any other requirements.

2021-09-29 03:18 UTC, silabs-LeiSun commented on README.md
> +Just ignore the setp of modification for TXCO controlling.
You can just ignore the steps of the modification for TXCO.

2021-09-29 03:23 UTC, silabs-LeiSun requested changes

2021-09-29 03:23 UTC, silabs-LeiSun commented on README.md
> +-  [KBA: Understanding DSSS Encoding and Decoding on EFR32 Devices](https://community.silabs.com/s/article/understanding-dsss-encoding-and-decoding-on-efr32-devices?language=en_US)
Add AN969 https://www.silabs.com/documents/public/application-notes/an969-measuring-power-consumption.pdf

2021-09-29 07:55 UTC, merged